name: test

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: cat>a.yml<<EOF
        aa
        bb
    - run: ls -a
    - run: nl a.yml
