name: test

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        echo aa > a.yml
        echo \n >> a.yml
        echo /n >> a.yml
    - run: ls -a
    - run: nl a.yml
