name: test

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: echo hero\nhore > ./a.yml
    - run: ls -a
    - run: nl a.yml
